name: Test

on:
  push:
    branches-ignore:
      - main # We require rebased topic branches making testing main moot.
    tags-ignore:
      - "**"
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go install tool
      - run: ginkgo -r ./...
        timeout-minutes: 10
